/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { XOLEInterface__factory } from "./XOLEInterface__factory";
export { XOLEStorage__factory } from "./XOLEStorage__factory";
