/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { COREToken } from "./COREToken";
export type { DAIToken } from "./DAIToken";
export type { DPIToken } from "./DPIToken";
export type { FEIToken } from "./FEIToken";
export type { FraxToken } from "./FraxToken";
export type { RAIToken } from "./RAIToken";
export type { UNIToken } from "./UNIToken";
export type { USDCToken } from "./USDCToken";
export type { USDTToken } from "./USDTToken";
export type { WBTCToken } from "./WBTCToken";
export type { WETHToken } from "./WETHToken";
export type { WISEToken } from "./WISEToken";
export type { XORToken } from "./XORToken";
