/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as arbitrum from "./arbitrum";
export type { arbitrum };
import type * as bsc from "./bsc";
export type { bsc };
import type * as cronos from "./cronos";
export type { cronos };
import type * as eth from "./eth";
export type { eth };
import type * as kcc from "./kcc";
export type { kcc };
export type { DexAggregatorDelegator } from "./DexAggregatorDelegator";
export type { DexAggregatorInterface } from "./DexAggregatorInterface";
