/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAggregationExecutor } from "./IAggregationExecutor";
export type { Mock1inchRouter } from "./Mock1inchRouter";
