/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lPoolInterfaceSol from "./LPoolInterface.sol";
export type { lPoolInterfaceSol };
export type { LPool } from "./LPool";
export type { LPoolDelegator } from "./LPoolDelegator";
export type { LPoolDepositor } from "./LPoolDepositor";
export type { LPoolDepositorDelegator } from "./LPoolDepositorDelegator";
export type { LTimePool } from "./LTimePool";
