/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as uniV2ClassDexSol from "./UniV2ClassDex.sol";
export { BscDexAggregatorV1__factory } from "./BscDexAggregatorV1__factory";
