/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as kccUniV2DexSol from "./KccUniV2Dex.sol";
export type { kccUniV2DexSol };
export type { KccDexAggregatorV1 } from "./KccDexAggregatorV1";
