/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as uniV2ClassDexSol from "./UniV2ClassDex.sol";
export type { uniV2ClassDexSol };
export type { BscDexAggregatorV1 } from "./BscDexAggregatorV1";
