/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OleLpStakeAutomatorInterface } from "./OleLpStakeAutomatorInterface";
export type { OleLpStakeAutomatorStorage } from "./OleLpStakeAutomatorStorage";
