/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as kccUniV2DexSol from "./KccUniV2Dex.sol";
export { KccDexAggregatorV1__factory } from "./KccDexAggregatorV1__factory";
