/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IKuswapPair,
  IKuswapPairInterface,
} from "../../../../../../contracts/udex/dex/kcc/KccUniV2Dex.sol/IKuswapPair";

const _abi = [
  {
    inputs: [],
    name: "swapFee",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IKuswapPair__factory {
  static readonly abi = _abi;
  static createInterface(): IKuswapPairInterface {
    return new Interface(_abi) as IKuswapPairInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IKuswapPair {
    return new Contract(address, _abi, runner) as unknown as IKuswapPair;
  }
}
