/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockDexAgg } from "./MockDexAgg";
export type { MockOpenLev } from "./MockOpenLev";
export type { MockToken } from "./MockToken";
