/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockDexAggInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getPrice"
      | "getPriceCAvgPriceHAvgPrice"
      | "setPrice"
      | "updatePriceOracle"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getPrice",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceCAvgPriceHAvgPrice",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrice",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePriceOracle",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPriceCAvgPriceHAvgPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updatePriceOracle",
    data: BytesLike
  ): Result;
}

export interface MockDexAgg extends BaseContract {
  connect(runner?: ContractRunner | null): MockDexAgg;
  waitForDeployment(): Promise<this>;

  interface: MockDexAggInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPrice: TypedContractMethod<
    [desToken: AddressLike, quoteToken: AddressLike, data: BytesLike],
    [[bigint, bigint] & { price: bigint; decimals: bigint }],
    "view"
  >;

  getPriceCAvgPriceHAvgPrice: TypedContractMethod<
    [
      desToken: AddressLike,
      quoteToken: AddressLike,
      secondsAgo: BigNumberish,
      dexData: BytesLike
    ],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        price: bigint;
        cAvgPrice: bigint;
        hAvgPrice: bigint;
        decimals: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  setPrice: TypedContractMethod<
    [
      price_: BigNumberish,
      cAvgPrice_: BigNumberish,
      hAvgPrice_: BigNumberish,
      timestamp_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  updatePriceOracle: TypedContractMethod<
    [
      desToken: AddressLike,
      quoteToken: AddressLike,
      timeWindow: BigNumberish,
      data: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<
    [desToken: AddressLike, quoteToken: AddressLike, data: BytesLike],
    [[bigint, bigint] & { price: bigint; decimals: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPriceCAvgPriceHAvgPrice"
  ): TypedContractMethod<
    [
      desToken: AddressLike,
      quoteToken: AddressLike,
      secondsAgo: BigNumberish,
      dexData: BytesLike
    ],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        price: bigint;
        cAvgPrice: bigint;
        hAvgPrice: bigint;
        decimals: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setPrice"
  ): TypedContractMethod<
    [
      price_: BigNumberish,
      cAvgPrice_: BigNumberish,
      hAvgPrice_: BigNumberish,
      timestamp_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePriceOracle"
  ): TypedContractMethod<
    [
      desToken: AddressLike,
      quoteToken: AddressLike,
      timeWindow: BigNumberish,
      data: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  filters: {};
}
